#!/bin/bash

echo "Build hook running"

VSC_REF=$(git rev-parse --short HEAD)

docker build -f Dockerfile.amd64 \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=${VSC_REF} \
             -t "${DOCKER_REPO}:amd64-latest" \
             -t "${DOCKER_REPO}:amd64-git${VSC_REF}" .

docker build -f Dockerfile.armv7 \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=${VSC_REF} \
             -t "${DOCKER_REPO}:armv7-latest" \
             -t "${DOCKER_REPO}:armv7-git${VSC_REF}" .
